### ISSUE TITLE
La documentation de Khiops visualization n'est pas en phase avec la version 11.0.2 diffusée avec Khiops 10.2.0

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops-pdf-docs#1]
L'onglet "Project info" est désormais le dernier onglet.

A noter: Khiops covisualization est encore en version 10.2.4, sans onglet, "Project info", et avec quelques bugs résiduel en cours de correction. Cf. action du board "Co-Visu 11.0.x en cours de stabilisation à intégrer via un patch"

Mettre à jour les guides au moment de l'intégration de la vesion stabilisée de Khiops covisualization

**Comment by carinehue** [comment]
à modifier également :  dans le paragraphe 3.First step, remplacer "khv file" par "json file"

**Comment by marcboulle** [comment]
Déjà pris en compte
